/**
 * Single source for command create/edit UI copy (labels, helper text).
 * Import from @/command-spec in command-edit sections, CreatePlaylistSyncDialog,
 * and shared widgets (ExpirationFields, PlexPlaylistTargetSection).
 */

export const commandUiCopy = {
  base: {
    displayNameLabel: "Display Name",
    descriptionLabel: "Description",
    dialogDescription: "Configure command settings and schedule",
  },
  schedule: {
    overrideLabel: "Override default schedule",
    cronPlaceholder: "0 3 * * *",
    cronHelp: "Cron format: minute hour day month weekday (e.g. 0 3 * * * = 3 AM daily)",
    usesGlobalDefault: "Uses global default (Config → Scheduler)",
    createCronPlaceholder: "0 6 * * *",
    createCronHelp: "Cron format: minute hour day month weekday (e.g. 0 6 * * * = daily at 6am)",
  },
  expiration: {
    enableLabel: "Enable expiration",
    helperDisabled: "When this time passes, the command will be disabled (not deleted).",
    helperWithPlaylistOption:
      "When this time passes, the command will be disabled (not deleted). Optionally remove its playlist from the target.",
    expiresAtLabel: "Expires at",
    deletePlaylistLabel: "Delete playlist from target when expired",
  },
  lastRun: { label: "Last Run" },
  lastStatus: { label: "Last Status", success: "Success", failed: "Failed" },
  plexPlaylistTarget: {
    syncToMultipleLabel: "Sync to multiple Plex users",
    helper:
      "Leave unchecked to use the server's primary account. Check the box to choose one or more Plex Home users (you can select a single user).",
    noAccounts: "No Plex accounts available",
  },
  playlistSync: {
    playlistUrlLabel: "Playlist URL",
    playlistUrlPlaceholder: "https://open.spotify.com/playlist/...",
    publicSourcesHelp: "Supports Spotify, Deezer public playlists",
    syncModeLabel: "Sync Mode",
    syncModeFull: "Full Sync",
    syncModeAppend: "Append Only",
    targetLabel: "Target",
    artistDiscovery: {
      checkboxLabel: "Add new artists",
      helper:
        "Artists discovered missing from Lidarr are added to the Playlist Sync Discovery import list. Discovery always runs to report counts; this controls whether to add.",
      maxLabel: "Max artists to add per run",
      maxHelper: "0 = no limit. First run adds none—only reports count.",
    },
  },
  listenbrainz: {
    playlistTypesLabel: "Playlist Types",
    retentionHeading: "Retention Settings",
    weeklyExploration: "Weekly Exploration",
    weeklyJams: "Weekly Jams",
    dailyJams: "Daily Jams",
    retentionHelper: "Number of playlists to keep for each type (older ones will be deleted)",
    cleanupCheckbox: "Enable playlist cleanup (delete old playlists)",
  },
  discoveryLastfm: {
    artistsToSample: "Lidarr artists to sample",
    artistsToSampleHelp: "Number of Lidarr artists to query Last.fm (1–100). Lower = faster.",
    artistCooldown: "Artist cooldown (days)",
    artistCooldownHelp: "Don't re-query an artist for this many days (1–365, default 30)",
    similarPerArtist: "Similar per artist",
    similarPerArtistHelp: "Similar artists to request per Lidarr artist (1–50)",
    outputLimit: "Output limit",
    outputLimitHelp: "Max artists in final output (1–50)",
    minMatchScore: "Min match score (0–1)",
    minMatchScoreHelp: "Minimum Last.fm match score (0–1, default 0.9)",
  },
  newReleases: {
    artistsPerRun: "Artists per run",
    artistsPerRunHelp: "Max artists to scan per batch (1–50)",
    releaseSource: "Release source",
    releaseTypesHeading: "Release types to include",
    releaseTypesHelp: "Used for batch runs and ad-hoc artist scans",
    sourceHelp: "Deezer uses public data; Spotify requires credentials in Config → Music Sources",
    deezerOption: "Deezer (no account configuration required)",
    spotifyOptionPrefix: "Spotify (",
    spotifyCredentialsOk: "credentials configured",
    spotifyCredentialsMissing: "set credentials in Config",
  },
  artistEvents: {
    artistsPerRun: "Artists per scheduled run",
    artistsPerRunHelp:
      "How many Lidarr artists to process each time the command runs (1–50). Artists never scanned or past their refresh time are chosen first. Default 20.",
    refreshTtl: "Per-artist refresh interval (days)",
    refreshTtlHelp:
      "After a successful fetch for an artist, wait this many days before they are due again (1–365).",
  },
  daylist: {
    plexAccountLabel: "Plex Account (play history source)",
    selectPlexPlaceholder: "Select Plex account",
    accountSuffixInUse: " (already has Daylist)",
    plexAccountHelp:
      "Plex Home users only. Daylist uses this account's play history. One Daylist per user.",
    runAtMinuteLabel: "Run at minute of hour (0–59)",
    runAtMinuteHelp:
      "Daylist runs hourly at this minute. Runs only when the day period changes (Dawn, Morning, etc.). Min: 0, max: 59.",
    excludePlayedLabel: "Exclude played (days)",
    excludePlayedHelp: "Skip tracks played in last N days. Min: 1, max: 30.",
    historyLookbackLabel: "History lookback (days)",
    historyLookbackHelp: "Days of play history to analyze. Min: 7, max: 365.",
    maxTracksLabel: "Max tracks",
    maxTracksHelp: "Target playlist size. Min: 10, max: 200.",
    advancedSummary: "Advanced settings",
    historicalRatioLabel: "Historical ratio:",
    historicalRatioHelp: "Share of tracks from history. Min: 0.1, max: 0.8.",
    sonicSimilarLimitLabel: "Sonically similar limit",
    sonicSimilarLimitHelp: "Max similar tracks per seed. Min: 1, max: 30.",
    sonicSimilarPlaylistLimitLabel: "Sonically similar playlist limit",
    sonicSimilarPlaylistLimitHelp:
      "Max tracks to fetch from Plex sonic API per request. Min: 10, max: 200.",
    sonicSimilarDistanceLabel: "Sonically similar distance:",
    sonicSimilarDistanceHelp: "0.1 = very similar, 2 = more diverse. Min: 0.1, max: 2.",
    usePrimaryMood: "Use primary mood for cover (default: secondary)",
    usePrimaryMoodHelp:
      "Cover text uses the second-most-common mood by default (Meloday). Enable to use the most common mood instead.",
    timezoneLabel: "Timezone (optional)",
    timezonePlaceholder: "e.g. America/New_York",
    timezoneHelp: "Leave empty to use scheduler timezone",
    timePeriodsLabel: "Time periods (Start–End hour, 0–23)",
    timePeriodsHelp:
      "When each period runs. Late Night wraps (e.g. 22–2 = 22,23,0,1,2). Hours 0–23.",
  },
  localDiscovery: {
    plexAccountLabel: "Plex Account (play history source)",
    selectPlaceholder: "Select account",
    accountSuffixInUse: " (already has Local Discovery)",
    plexAccountHelp:
      "Plex Home users only. Local Discovery uses this account's play history. One Local Discovery per user.",
    lookbackDaysLabel: "Lookback days",
    lookbackDaysHelp:
      "How far back to count plays. Shorter = more day-to-day variety. Min: 7, max: 365.",
    excludePlayedLabel: "Exclude played days",
    excludePlayedHelp: "Skip tracks played in last N days. Reduces repetition. Min: 0, max: 30.",
    topArtistsCountLabel: "Top artists count",
    topArtistsCountHelp: "How many top artists to randomly pick each run. Min: 1, max: 20.",
    artistPoolSizeLabel: "Artist pool size",
    artistPoolSizeHelp:
      "Size of artist pool to sample from (must be ≥ top artists count). Min: top artists, max: 50.",
    maxTracksLabel: "Max tracks",
    maxTracksHelp: "Target playlist size. Min: 1, max: 200.",
    sonicSimilarLimitLabel: "Sonic similar limit",
    sonicSimilarLimitHelp: "Max sonically similar tracks per seed. Min: 5, max: 50.",
    sonicSimilarityDistanceLabel: "Sonic similarity distance",
    sonicSimilarityDistanceHelp: "Plex sonic match threshold. Lower = stricter. Min: 0.1, max: 1.",
    historicalRatioLabel: "Historical ratio:",
    historicalRatioHelp:
      "Share of tracks from play history vs sonically similar. 0.3 = 30% history, 70% similar.",
  },
  moodPlaylist: {
    moodsHeading: "Moods (select one or more)",
    loadingMoods: "Loading moods...",
    rankingHelper: "Tracks matching multiple selected moods rank higher. Uses Plex Sonic Analysis.",
    useCustomPlaylistName: "Use custom playlist name",
    customPlaylistNameLabel: "Custom playlist name",
    customPlaylistPlaceholder: "e.g. Chill Vibes",
    customPlaylistNameHelper: "Override auto-generated name. Shown as [Cmdarr] Mood: <name>.",
    autoNameHelp:
      "Playlist name is auto-generated from mood names (e.g. Chill · Relaxed + 2 More).",
    maxTracksLabel: "Max tracks",
    maxTracksHelp: "Min 1, max 200",
    forceFresh: "Force fresh (exclude tracks from previous run)",
    limitByYear: "Limit by release year (album year)",
    minYear: "Min year",
    maxYear: "Max year",
    minYearPlaceholder: "e.g. 1990",
    maxYearPlaceholder: "e.g. 2010",
    yearRangeHelp:
      "Set min and/or max. Tracks without year metadata are excluded. Range: 1800–2100.",
  },
  topTracks: {
    targetReadOnlyHelp: "Create a new command to change Plex or Jellyfin.",
    artistsLabel: "Artists (one per line)",
    artistsHelp:
      "Artists must exist in your library. Names are validated against the library cache.",
    artistsPlaceholder: "Artist One\nArtist Two\nArtist Three",
    topXLabel: "Top X per artist",
    topXLabelCreate: "Top X tracks per artist",
    topXHelp: "Number of top tracks per artist. Min: 1, max: 20.",
    useCustomPlaylistName: "Use custom playlist name",
    customPlaylistNameLabel: "Custom playlist name",
    customPlaylistPlaceholder: "e.g. Road Trip Mix",
    customPlaylistNameHelper:
      "Override auto-generated name. Shown as [Cmdarr] Artist Essentials: <name>.",
    autoNameHelp:
      "Playlist name is auto-generated from artist names (e.g. Artist1 · Artist2 + 3 More).",
    sourceLabel: "Source",
    sourceLabelCreate: "Source (Jellyfin target uses Last.fm only)",
    sourceHelp: "Plex uses ratingCount; Last.fm uses play counts. Jellyfin requires Last.fm.",
    targetLabel: "Target",
    targetWhereHelp: "Where to create the playlist.",
    plexOptionRating: "Plex (ratingCount)",
    lastfmOption: "Last.fm",
  },
  lfmSimilar: {
    targetReadOnlyHelp: "Create a new command to change Plex or Jellyfin.",
    seedArtistsLabel: "Seed artists (one per line)",
    seedArtistsHelp:
      "Expanded via Last.fm similar artists. Final artists must exist in your library (library cache).",
    seedArtistsPlaceholder: "Radiohead\nMiles Davis",
    similarPerSeedLabel: "Similar artists per seed",
    similarPerSeedHelp: "How many similar artists to request from Last.fm per seed (1–50).",
    maxArtistsLabel: "Max artists in playlist pool",
    maxArtistsHelp:
      "After merging similar results (round-robin across seeds), cap total unique artists (1–200).",
    includeSeedsLabel: "Include seed artists in the playlist",
    includeSeedsHelp: "When enabled, seeds are added first; similar artists fill remaining slots.",
    topXLabel: "Top X tracks per artist",
    topXHelp: "Last.fm top tracks per library-matched artist. Min: 1, max: 20.",
    useCustomPlaylistName: "Use custom playlist name",
    customPlaylistNameLabel: "Custom playlist name",
    customPlaylistPlaceholder: "e.g. Neighbors Mix",
    customPlaylistNameHelper:
      "Override auto-generated name. Shown as [Cmdarr] Last.fm Similar: <name>.",
    autoNameHelp:
      "Playlist title uses seed artist names only (not every similar name), e.g. Artist1 · Artist2 + 1 More.",
    targetLabel: "Target",
    targetWhereHelp: "Where to create the playlist. Charts always come from Last.fm.",
    lastfmNote: "Track list uses Last.fm top tracks, matched to your library.",
  },
  setlistFm: {
    targetReadOnlyHelp: "Create a new command to change Plex or Jellyfin.",
    artistsLabel: "Artists (one per line, in order)",
    artistsHelp:
      "Artists must exist in your library. Each line becomes one block of recent setlist.fm tracks in that order.",
    artistsPlaceholder: "Artist One\nArtist Two\nArtist Three",
    maxTracksPerArtistLabel: "Max tracks per artist (per block)",
    maxTracksPerArtistHelp: "From recent setlists. Min: 3, max: 30.",
    maxSetlistPagesLabel: "Max setlist.fm pages to scan per artist",
    maxSetlistPagesHelp: "Pagination cap when searching setlists. Min: 1, max: 20.",
    setlistNote: "Requires SETLIST_FM_API_KEY in Config (Music Sources → setlist.fm).",
    useCustomPlaylistName: "Use custom playlist name",
    customPlaylistNameLabel: "Custom playlist name",
    customPlaylistPlaceholder: "e.g. Summer Tour 2024",
    customPlaylistNameHelper: "Override auto-generated name. Shown as [Cmdarr] Setlist: <name>.",
    autoNameHelp:
      "Playlist title uses artist names from your list (e.g. Artist1 · Artist2 + 1 More).",
    targetLabel: "Target",
    targetWhereHelp: "Where to create the playlist.",
  },
  xmplaylist: {
    sourceLockedHint: "Source mode is fixed after creation.",
    targetReadOnlyLabel: "Target",
    targetReadOnlyHelp: "Create a new command to change Plex or Jellyfin.",
    stationLabel: "Station",
    filterStationsPlaceholder: "Filter stations…",
    currentSelectionPrefix: "Current:",
    loadingEllipsis: "Loading…",
    playlistModeLabel: "Source",
    daysLabel: "Days",
    maxTracksLabel: "Max tracks",
    maxTracksHelpRange: "Between 1 and 50.",
    modeDisplayNewest: "Newest",
    modeDisplayMostPlayed: "Most played",
    stationSearchHint: "Search by channel number or name. Sorted by channel number.",
    selectedStationLabel: "Selected:",
    noStationSelected: "No station selected",
    loadingStations: "Loading stations…",
    noStationsMatch: "No stations match.",
    playlistSourceLabel: "Playlist source",
    newestTracksOption: "Newest tracks",
    mostPlayedOption: "Most played",
    timePeriodLabel: "Time period",
    maxTracksInPlaylistLabel: "Max tracks in playlist",
    period1Day: "1 day",
    period7Days: "7 days",
    period14Days: "14 days",
    period30Days: "30 days",
    period60Days: "60 days",
  },
  createWizard: {
    titleChooseType: "Create New Command",
    titleDaylist: "Configure Daylist",
    titleArtistEssentials: "Configure Artist Essentials",
    titleLfmSimilar: "Configure Last.fm Similar",
    titleSetlistFm: "Configure Setlist.fm Playlist",
    titleLocalDiscovery: "Configure Local Discovery",
    titleMoodPlaylist: "Configure Mood Playlist",
    titleXmplaylist: "Configure XMPlaylist (SiriusXM History)",
    titleListenbrainz: "Configure ListenBrainz Playlist",
    titleExternal: "Configure External Playlist",
    descChooseType: "Choose the type of command to create",
    descDaylist: "Configure your daylist settings",
    descTopTracks: "Artists must exist in your library. One artist per line.",
    descLfmSimilar:
      "Seed artists → Last.fm similar → top tracks per artist. Requires Last.fm API key in config.",
    descSetlistFm:
      "Ordered artist list → recent setlist.fm songs per artist → matched to your library. Requires Setlist.fm API key.",
    descLocalDiscovery: "Top artists from play history + sonically similar tracks. Fresh each run.",
    descMoodPlaylist:
      "Select moods from Plex Sonic Analysis. Tracks matching multiple moods rank higher.",
    descXmplaylist:
      "Data from xmplaylist.com. Tracks are matched to your Plex or Jellyfin library.",
    descDefault: "Configure your playlist sync settings",
    cardDaylistTitle: "Daylist",
    cardDaylistBlurb:
      "Time-of-day playlists from Plex listening history and Sonic Analysis. Plex only.",
    cardLocalDiscoveryTitle: "Local Discovery",
    cardLocalDiscoveryBlurb:
      "Top artists from play history + sonically similar tracks. Fresh each run. Plex only.",
    cardListenbrainzTitle: "ListenBrainz Curated",
    cardListenbrainzBlurb: "Sync Weekly Exploration, Weekly Jams, or Daily Jams playlists",
    cardExternalTitle: "External Playlist",
    cardExternalBlurb: "Sync public playlists from Spotify, Deezer, or other sources",
    cardArtistEssentialsTitle: "Artist Essentials",
    cardArtistEssentialsBlurb:
      "Generate playlist from artist list with top X tracks per artist (Plex or Last.fm).",
    cardLfmSimilarTitle: "Last.fm Similar",
    cardLfmSimilarBlurb:
      "Expand seed artists with Last.fm similar, then top tracks per library-matched artist.",
    cardSetlistFmTitle: "Setlist.fm",
    cardSetlistFmBlurb:
      "Build a playlist from recent live setlists on setlist.fm, one ordered block per artist.",
    cardXmplaylistTitle: "XMPlaylist (SiriusXM History)",
    cardXmplaylistBlurb:
      "Newest or most-played tracks per station via xmplaylist.com → Plex or Jellyfin.",
    cardMoodTitle: "Mood Playlist",
    cardMoodBlurb: "Generate from selected Plex moods. Fresh each run with exclude-last-run.",
    enableAfterCreation: "Enable immediately after creation",
    submitCreating: "Creating...",
    submitDaylist: "Create Daylist",
    submitArtistEssentials: "Create Artist Essentials",
    submitLfmSimilar: "Create Last.fm Similar",
    submitSetlistFm: "Create Setlist.fm Playlist",
    submitLocalDiscovery: "Create Local Discovery",
    submitXmplaylist: "Create XMPlaylist",
    submitPlaylistSync: "Create Playlist Sync",
    submitMoodPlaylist: "Create Mood Playlist",
  },
} as const;
